spring.application.name=quan-ly-nha-hang-APIs

spring.datasource.url=jdbc:mysql://localhost:3306/quan-ly-nha-hang?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=npq24102005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.servlet.context-path=/api

jwt.secret=longtoitannatkhinhanraClaudePROdalayditatcahuhuhuhuhuhuhuhuhuhuhuhuhu124810@$@@$^&^&*&!$^$!&^*$!*&(R^|Ươ]ơ\ơ}|Ơ|Ư
jwt.expiration=86400000

spring.security.NguoiDung.taiKhoan=admin
spring.security.NguoiDung.matKhau=12345678